<?php
namespace EspritApiBundle\Repository;

use Doctrine\ORM\EntityRepository;
use BlogBundle\Entity\Post;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\Query;

use Doctrine\ORM\QueryBuilder;



/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{





}
